/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as RoutinesNewRouteImport } from './routes/routines_.new'
import { Route as RoutinesIdRouteImport } from './routes/routines_.$id'
import { Route as PlansNewRouteImport } from './routes/plans_.new'
import { Route as PlansIdRouteImport } from './routes/plans_.$id'
import { Route as CoachIdRouteImport } from './routes/coach.$id'

const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesNewRoute = RoutinesNewRouteImport.update({
  id: '/routines_/new',
  path: '/routines/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIdRoute = RoutinesIdRouteImport.update({
  id: '/routines_/$id',
  path: '/routines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/plans_/new',
  path: '/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIdRoute = PlansIdRouteImport.update({
  id: '/plans_/$id',
  path: '/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIdRoute = CoachIdRouteImport.update({
  id: '/coach/$id',
  path: '/coach/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routines': typeof RoutinesRoute
  '/coach/$id': typeof CoachIdRoute
  '/plans/$id': typeof PlansIdRoute
  '/plans/new': typeof PlansNewRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/routines/new': typeof RoutinesNewRoute
  '/workout/$id': typeof WorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/routines': typeof RoutinesRoute
  '/coach/$id': typeof CoachIdRoute
  '/plans/$id': typeof PlansIdRoute
  '/plans/new': typeof PlansNewRoute
  '/routines/$id': typeof RoutinesIdRoute
  '/routines/new': typeof RoutinesNewRoute
  '/workout/$id': typeof WorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/routines': typeof RoutinesRoute
  '/coach/$id': typeof CoachIdRoute
  '/plans_/$id': typeof PlansIdRoute
  '/plans_/new': typeof PlansNewRoute
  '/routines_/$id': typeof RoutinesIdRoute
  '/routines_/new': typeof RoutinesNewRoute
  '/workout/$id': typeof WorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/routines'
    | '/coach/$id'
    | '/plans/$id'
    | '/plans/new'
    | '/routines/$id'
    | '/routines/new'
    | '/workout/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/routines'
    | '/coach/$id'
    | '/plans/$id'
    | '/plans/new'
    | '/routines/$id'
    | '/routines/new'
    | '/workout/$id'
  id:
    | '__root__'
    | '/'
    | '/routines'
    | '/coach/$id'
    | '/plans_/$id'
    | '/plans_/new'
    | '/routines_/$id'
    | '/routines_/new'
    | '/workout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoutinesRoute: typeof RoutinesRoute
  CoachIdRoute: typeof CoachIdRoute
  PlansIdRoute: typeof PlansIdRoute
  PlansNewRoute: typeof PlansNewRoute
  RoutinesIdRoute: typeof RoutinesIdRoute
  RoutinesNewRoute: typeof RoutinesNewRoute
  WorkoutIdRoute: typeof WorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines_/new': {
      id: '/routines_/new'
      path: '/routines/new'
      fullPath: '/routines/new'
      preLoaderRoute: typeof RoutinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines_/$id': {
      id: '/routines_/$id'
      path: '/routines/$id'
      fullPath: '/routines/$id'
      preLoaderRoute: typeof RoutinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans_/new': {
      id: '/plans_/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans_/$id': {
      id: '/plans_/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof PlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$id': {
      id: '/coach/$id'
      path: '/coach/$id'
      fullPath: '/coach/$id'
      preLoaderRoute: typeof CoachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoutinesRoute: RoutinesRoute,
  CoachIdRoute: CoachIdRoute,
  PlansIdRoute: PlansIdRoute,
  PlansNewRoute: PlansNewRoute,
  RoutinesIdRoute: RoutinesIdRoute,
  RoutinesNewRoute: RoutinesNewRoute,
  WorkoutIdRoute: WorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
